-- Insert 500 technology-related tags for testing tag cloud visualization
-- Tags are created without user (created_by = NULL) to be publicly accessible
-- Color palette using technology-themed colors

INSERT INTO tags (name, description, color, created_by) VALUES
-- Programming Languages & Frameworks (50 tags)
('JavaScript', 'Popular web programming language', '#F7DF1E', NULL),
('Python', 'Versatile programming language', '#3776AB', NULL),
('TypeScript', 'Typed superset of JavaScript', '#3178C6', NULL),
('React', 'JavaScript library for building UIs', '#61DAFB', NULL),
('Vue.js', 'Progressive JavaScript framework', '#4FC08D', NULL),
('Angular', 'Platform for building mobile and desktop apps', '#DD0031', NULL),
('Node.js', 'JavaScript runtime environment', '#339933', NULL),
('Django', 'Python web framework', '#092E20', NULL),
('Flask', 'Micro web framework for Python', '#000000', NULL),
('Ruby on Rails', 'Web application framework', '#CC0000', NULL),
('Java', 'Object-oriented programming language', '#007396', NULL),
('C++', 'High-performance programming language', '#00599C', NULL),
('C#', 'Modern object-oriented language', '#239120', NULL),
('PHP', 'Server-side scripting language', '#777BB4', NULL),
('Swift', 'Programming language for iOS', '#FA7343', NULL),
('Kotlin', 'Modern programming language for Android', '#0095D5', NULL),
('Go', 'Compiled programming language by Google', '#00ADD8', NULL),
('Rust', 'Systems programming language', '#000000', NULL),
('Scala', 'Functional and object-oriented language', '#DC322F', NULL),
('Elixir', 'Functional programming language', '#4B275F', NULL),
('Dart', 'Programming language for Flutter', '#0175C2', NULL),
('R', 'Statistical computing language', '#276DC3', NULL),
('Julia', 'High-performance technical computing', '#9558B2', NULL),
('Perl', 'High-level programming language', '#39457E', NULL),
('Haskell', 'Purely functional programming language', '#5D4F85', NULL),
('Clojure', 'Dynamic functional programming language', '#5881D8', NULL),
('F#', 'Functional-first programming language', '#378BBA', NULL),
('Lua', 'Lightweight programming language', '#2C2D72', NULL),
('Assembly', 'Low-level programming language', '#6E4C13', NULL),
('COBOL', 'Business-oriented programming language', '#004B87', NULL),
('Fortran', 'Scientific computing language', '#734F96', NULL),
('Next.js', 'React framework for production', '#000000', NULL),
('Nuxt.js', 'Vue.js framework', '#00C58E', NULL),
('Express.js', 'Web framework for Node.js', '#000000', NULL),
('FastAPI', 'Modern Python web framework', '#009688', NULL),
('Spring Boot', 'Java framework', '#6DB33F', NULL),
('Laravel', 'PHP web framework', '#FF2D20', NULL),
('Symfony', 'PHP framework', '#000000', NULL),
('ASP.NET', 'Web framework by Microsoft', '#512BD4', NULL),
('Svelte', 'Cybernetically enhanced web apps', '#FF3E00', NULL),
('Ember.js', 'Framework for ambitious web developers', '#E04E39', NULL),
('Backbone.js', 'JavaScript framework', '#0071B5', NULL),
('Redux', 'State management library', '#764ABC', NULL),
('MobX', 'Simple state management', '#FF9955', NULL),
('GraphQL', 'Query language for APIs', '#E10098', NULL),
('REST API', 'Representational State Transfer', '#FF6C37', NULL),
('WebSockets', 'Real-time communication protocol', '#010101', NULL),
('gRPC', 'High-performance RPC framework', '#244c5a', NULL),
('Webpack', 'Module bundler', '#8DD6F9', NULL),
('Vite', 'Next generation frontend tooling', '#646CFF', NULL),

-- Databases & Data Storage (40 tags)
('PostgreSQL', 'Open source relational database', '#336791', NULL),
('MySQL', 'Popular open source database', '#4479A1', NULL),
('MongoDB', 'NoSQL document database', '#47A248', NULL),
('Redis', 'In-memory data structure store', '#DC382D', NULL),
('SQLite', 'Lightweight database engine', '#003B57', NULL),
('MariaDB', 'MySQL fork', '#003545', NULL),
('Oracle Database', 'Enterprise database system', '#F80000', NULL),
('Microsoft SQL Server', 'Relational database system', '#CC2927', NULL),
('Cassandra', 'Distributed NoSQL database', '#1287B1', NULL),
('Elasticsearch', 'Search and analytics engine', '#005571', NULL),
('DynamoDB', 'AWS NoSQL database', '#4053D6', NULL),
('CouchDB', 'Document-oriented NoSQL database', '#E42528', NULL),
('Neo4j', 'Graph database platform', '#008CC1', NULL),
('InfluxDB', 'Time series database', '#22ADF6', NULL),
('TimescaleDB', 'Time-series SQL database', '#FDB515', NULL),
('Firebase', 'Google mobile platform', '#FFCA28', NULL),
('Supabase', 'Open source Firebase alternative', '#3ECF8E', NULL),
('Firestore', 'NoSQL cloud database', '#FFCA28', NULL),
('RethinkDB', 'Real-time database', '#1F5082', NULL),
('ArangoDB', 'Multi-model database', '#DDE072', NULL),
('RavenDB', 'NoSQL document database', '#E83828', NULL),
('OrientDB', 'Multi-model database', '#33A3DC', NULL),
('VoltDB', 'In-memory database', '#2E7D32', NULL),
('MemSQL', 'Distributed SQL database', '#0099CC', NULL),
('CockroachDB', 'Distributed SQL database', '#6933FF', NULL),
('Realm', 'Mobile database', '#39477F', NULL),
('IndexedDB', 'Browser database API', '#FF9800', NULL),
('LocalStorage', 'Web storage API', '#FFC107', NULL),
('SessionStorage', 'Temporary web storage', '#FF9800', NULL),
('Hadoop', 'Big data framework', '#66CCFF', NULL),
('Apache Spark', 'Unified analytics engine', '#E25A1C', NULL),
('Apache Kafka', 'Distributed streaming platform', '#000000', NULL),
('RabbitMQ', 'Message broker', '#FF6600', NULL),
('Apache Flink', 'Stream processing framework', '#E6526F', NULL),
('Apache Hive', 'Data warehouse software', '#FDEE21', NULL),
('Apache HBase', 'Non-relational distributed database', '#1E8CBE', NULL),
('Memcached', 'Distributed memory caching system', '#4A90E2', NULL),
('Couchbase', 'NoSQL cloud database', '#EA2328', NULL),
('Snowflake', 'Cloud data platform', '#29B5E8', NULL),
('BigQuery', 'Google data warehouse', '#4285F4', NULL),

-- Cloud & DevOps (60 tags)
('AWS', 'Amazon Web Services', '#FF9900', NULL),
('Azure', 'Microsoft cloud platform', '#0089D6', NULL),
('Google Cloud', 'Google cloud platform', '#4285F4', NULL),
('Docker', 'Container platform', '#2496ED', NULL),
('Kubernetes', 'Container orchestration', '#326CE5', NULL),
('Jenkins', 'Automation server', '#D24939', NULL),
('GitLab CI/CD', 'DevOps platform', '#FCA121', NULL),
('GitHub Actions', 'CI/CD automation', '#2088FF', NULL),
('CircleCI', 'Continuous integration platform', '#343434', NULL),
('Travis CI', 'Continuous integration service', '#3EAAAF', NULL),
('Terraform', 'Infrastructure as code', '#7B42BC', NULL),
('Ansible', 'IT automation platform', '#EE0000', NULL),
('Puppet', 'Configuration management', '#FFAE1A', NULL),
('Chef', 'Configuration management tool', '#F09820', NULL),
('Vagrant', 'Development environment manager', '#1563FF', NULL),
('Heroku', 'Cloud platform as a service', '#430098', NULL),
('DigitalOcean', 'Cloud infrastructure provider', '#0080FF', NULL),
('Linode', 'Cloud hosting provider', '#00A95C', NULL),
('Vercel', 'Frontend cloud platform', '#000000', NULL),
('Netlify', 'Web development platform', '#00C7B7', NULL),
('CloudFlare', 'Web infrastructure company', '#F38020', NULL),
('Nginx', 'Web server and reverse proxy', '#009639', NULL),
('Apache', 'HTTP server', '#D22128', NULL),
('HAProxy', 'Load balancer', '#7AC143', NULL),
('Consul', 'Service mesh solution', '#F24C53', NULL),
('Prometheus', 'Monitoring system', '#E6522C', NULL),
('Grafana', 'Analytics and monitoring', '#F46800', NULL),
('Datadog', 'Monitoring and analytics', '#632CA6', NULL),
('New Relic', 'Application performance monitoring', '#008C99', NULL),
('Splunk', 'Data analysis platform', '#000000', NULL),
('ELK Stack', 'Elasticsearch Logstash Kibana', '#005571', NULL),
('Istio', 'Service mesh', '#466BB0', NULL),
('Linkerd', 'Service mesh for Kubernetes', '#2DCEA3', NULL),
('OpenShift', 'Kubernetes container platform', '#EE0000', NULL),
('Rancher', 'Kubernetes management platform', '#0075A8', NULL),
('Nomad', 'Workload orchestrator', '#00CA8E', NULL),
('Mesos', 'Cluster manager', '#0D7FA0', NULL),
('Swarm', 'Docker native clustering', '#2496ED', NULL),
('Portainer', 'Container management tool', '#13BEF9', NULL),
('AWS Lambda', 'Serverless compute service', '#FF9900', NULL),
('Azure Functions', 'Serverless compute', '#0089D6', NULL),
('Cloud Functions', 'Google serverless platform', '#4285F4', NULL),
('OpenFaaS', 'Serverless functions framework', '#3F51B5', NULL),
('Knative', 'Kubernetes-based serverless', '#0E83C2', NULL),
('Serverless Framework', 'Build serverless apps', '#FD5750', NULL),
('AWS EC2', 'Virtual servers in cloud', '#FF9900', NULL),
('AWS S3', 'Object storage service', '#569A31', NULL),
('AWS RDS', 'Managed database service', '#527FFF', NULL),
('AWS ECS', 'Container orchestration', '#FF9900', NULL),
('AWS EKS', 'Managed Kubernetes', '#FF9900', NULL),
('Azure DevOps', 'Development collaboration tools', '#0078D7', NULL),
('Azure Kubernetes', 'Managed Kubernetes service', '#326CE5', NULL),
('Google Kubernetes Engine', 'Managed Kubernetes', '#4285F4', NULL),
('CloudFormation', 'AWS infrastructure as code', '#FF9900', NULL),
('ARM Templates', 'Azure infrastructure as code', '#0089D6', NULL),
('Pulumi', 'Modern infrastructure as code', '#8A3391', NULL),
('SaltStack', 'Configuration management', '#00EACE', NULL),
('Packer', 'Machine image builder', '#02A8EF', NULL),
('Vault', 'Secrets management', '#000000', NULL),
('Kong', 'API gateway', '#003459', NULL),

-- AI & Machine Learning (50 tags)
('Machine Learning', 'Algorithms that learn from data', '#FF6F00', NULL),
('Deep Learning', 'Neural networks with multiple layers', '#FF6D00', NULL),
('Neural Networks', 'Computing systems inspired by brain', '#9C27B0', NULL),
('TensorFlow', 'Open source ML framework', '#FF6F00', NULL),
('PyTorch', 'Machine learning library', '#EE4C2C', NULL),
('Keras', 'Deep learning API', '#D00000', NULL),
('Scikit-learn', 'Machine learning library', '#F7931E', NULL),
('OpenCV', 'Computer vision library', '#5C3EE8', NULL),
('Natural Language Processing', 'AI understanding of language', '#4CAF50', NULL),
('Computer Vision', 'AI understanding of images', '#2196F3', NULL),
('Reinforcement Learning', 'Learning through rewards', '#9C27B0', NULL),
('Supervised Learning', 'Learning from labeled data', '#4CAF50', NULL),
('Unsupervised Learning', 'Learning from unlabeled data', '#FF9800', NULL),
('Transfer Learning', 'Reusing learned models', '#3F51B5', NULL),
('Generative AI', 'AI that creates content', '#E91E63', NULL),
('GPT', 'Generative Pre-trained Transformer', '#10A37F', NULL),
('BERT', 'Bidirectional Encoder Representations', '#4285F4', NULL),
('Transformers', 'Attention-based neural networks', '#FFD21E', NULL),
('Large Language Models', 'Massive text-processing models', '#8E24AA', NULL),
('ChatGPT', 'Conversational AI model', '#10A37F', NULL),
('Stable Diffusion', 'Text-to-image AI model', '#7C3AED', NULL),
('DALL-E', 'Image generation AI', '#10A37F', NULL),
('Midjourney', 'AI image generation tool', '#000000', NULL),
('Hugging Face', 'ML model repository', '#FFD21E', NULL),
('MLflow', 'ML lifecycle platform', '#0194E2', NULL),
('Weights & Biases', 'ML experiment tracking', '#FFBE00', NULL),
('AutoML', 'Automated machine learning', '#4285F4', NULL),
('Feature Engineering', 'Creating input variables', '#00BCD4', NULL),
('Data Augmentation', 'Expanding training datasets', '#9C27B0', NULL),
('Convolutional Neural Networks', 'Deep learning for images', '#673AB7', NULL),
('Recurrent Neural Networks', 'Networks with memory', '#3F51B5', NULL),
('GANs', 'Generative Adversarial Networks', '#E91E63', NULL),
('XGBoost', 'Gradient boosting library', '#FF6B6B', NULL),
('LightGBM', 'Gradient boosting framework', '#9C27B0', NULL),
('CatBoost', 'Gradient boosting library', '#FFCC00', NULL),
('Random Forest', 'Ensemble learning method', '#4CAF50', NULL),
('Decision Trees', 'Tree-based prediction model', '#8BC34A', NULL),
('SVM', 'Support Vector Machines', '#FF5722', NULL),
('K-Means', 'Clustering algorithm', '#00BCD4', NULL),
('Principal Component Analysis', 'Dimensionality reduction', '#9C27B0', NULL),
('Gradient Descent', 'Optimization algorithm', '#FF9800', NULL),
('Backpropagation', 'Neural network training', '#3F51B5', NULL),
('Ensemble Learning', 'Combining multiple models', '#4CAF50', NULL),
('Model Deployment', 'Putting models into production', '#2196F3', NULL),
('MLOps', 'ML operations practices', '#FF6F00', NULL),
('AI Ethics', 'Responsible AI development', '#9C27B0', NULL),
('Explainable AI', 'Interpretable machine learning', '#00BCD4', NULL),
('Edge AI', 'AI on edge devices', '#4CAF50', NULL),
('Federated Learning', 'Distributed ML training', '#3F51B5', NULL),
('Quantum Machine Learning', 'ML with quantum computers', '#9C27B0', NULL),

-- Web Technologies (50 tags)
('HTML5', 'Markup language for web', '#E34F26', NULL),
('CSS3', 'Styling language for web', '#1572B6', NULL),
('Sass', 'CSS preprocessor', '#CC6699', NULL),
('Less', 'CSS preprocessor', '#1D365D', NULL),
('Tailwind CSS', 'Utility-first CSS framework', '#06B6D4', NULL),
('Bootstrap', 'CSS framework', '#7952B3', NULL),
('Material-UI', 'React UI framework', '#0081CB', NULL),
('Ant Design', 'Enterprise UI design system', '#0170FE', NULL),
('Chakra UI', 'Modular component library', '#319795', NULL),
('Styled Components', 'CSS-in-JS library', '#DB7093', NULL),
('Emotion', 'CSS-in-JS library', '#D36AC2', NULL),
('PostCSS', 'CSS transformation tool', '#DD3A0A', NULL),
('jQuery', 'JavaScript library', '#0769AD', NULL),
('AJAX', 'Asynchronous JavaScript', '#0099CC', NULL),
('JSON', 'JavaScript Object Notation', '#000000', NULL),
('XML', 'Extensible Markup Language', '#0060AC', NULL),
('YAML', 'Data serialization language', '#CB171E', NULL),
('Markdown', 'Lightweight markup language', '#000000', NULL),
('Progressive Web Apps', 'Web apps with native features', '#5A0FC8', NULL),
('Service Workers', 'Background web scripts', '#F16529', NULL),
('Web Components', 'Reusable web elements', '#29ABE2', NULL),
('Shadow DOM', 'Encapsulated DOM', '#E44D26', NULL),
('Single Page Application', 'Web app in single page', '#41B883', NULL),
('Server-Side Rendering', 'Rendering on server', '#000000', NULL),
('Static Site Generation', 'Pre-rendering at build time', '#000000', NULL),
('JAMstack', 'JavaScript APIs Markup', '#F0047F', NULL),
('Headless CMS', 'Content management system', '#0080FF', NULL),
('WordPress', 'Content management system', '#21759B', NULL),
('Drupal', 'Content management framework', '#0678BE', NULL),
('Joomla', 'Content management system', '#5091CD', NULL),
('Contentful', 'Headless CMS', '#2478CC', NULL),
('Strapi', 'Open source headless CMS', '#2F2E8B', NULL),
('Sanity', 'Platform for structured content', '#F03E2F', NULL),
('Ghost', 'Publishing platform', '#15171A', NULL),
('Hugo', 'Static site generator', '#FF4088', NULL),
('Jekyll', 'Static site generator', '#CC0000', NULL),
('Gatsby', 'React-based framework', '#663399', NULL),
('Eleventy', 'Static site generator', '#000000', NULL),
('Astro', 'All-in-one web framework', '#FF5D01', NULL),
('Web Accessibility', 'Inclusive web design', '#0078D7', NULL),
('ARIA', 'Accessible Rich Internet Applications', '#0078D7', NULL),
('WCAG', 'Web Content Accessibility Guidelines', '#005A9C', NULL),
('Responsive Design', 'Multi-device web design', '#3DDC84', NULL),
('Mobile-First Design', 'Design for mobile first', '#4285F4', NULL),
('Cross-Browser Compatibility', 'Works across browsers', '#E44D26', NULL),
('Web Performance', 'Optimizing website speed', '#FF6D00', NULL),
('Lighthouse', 'Web performance tool', '#F44B21', NULL),
('WebAssembly', 'Binary instruction format', '#654FF0', NULL),
('WebGL', '3D graphics for web', '#990000', NULL),
('Three.js', '3D JavaScript library', '#000000', NULL),

-- Mobile Development (30 tags)
('iOS Development', 'Apple mobile development', '#000000', NULL),
('Android Development', 'Google mobile development', '#3DDC84', NULL),
('React Native', 'Cross-platform mobile framework', '#61DAFB', NULL),
('Flutter', 'Google UI toolkit', '#02569B', NULL),
('Xamarin', 'Microsoft mobile framework', '#3498DB', NULL),
('Ionic', 'Hybrid mobile framework', '#3880FF', NULL),
('Cordova', 'Mobile development framework', '#E8E8E8', NULL),
('SwiftUI', 'UI framework for iOS', '#FA7343', NULL),
('Jetpack Compose', 'Android UI toolkit', '#4285F4', NULL),
('NativeScript', 'Mobile framework', '#3655FF', NULL),
('Capacitor', 'Cross-platform runtime', '#119EFF', NULL),
('Expo', 'React Native platform', '#000020', NULL),
('Android Studio', 'Android IDE', '#3DDC84', NULL),
('Xcode', 'Apple development IDE', '#147EFB', NULL),
('TestFlight', 'iOS beta testing', '#0D96F6', NULL),
('App Store', 'Apple app marketplace', '#0D96F6', NULL),
('Google Play', 'Android app marketplace', '#414141', NULL),
('Mobile UI/UX', 'Mobile user experience', '#FF6B6B', NULL),
('Push Notifications', 'Mobile alerts', '#FF9500', NULL),
('In-App Purchases', 'Mobile monetization', '#34C759', NULL),
('Mobile Analytics', 'App usage tracking', '#4A90E2', NULL),
('Firebase Analytics', 'Google app analytics', '#FFCA28', NULL),
('AdMob', 'Mobile advertising', '#EA4335', NULL),
('Mobile Security', 'App security practices', '#FF3B30', NULL),
('Biometric Authentication', 'Fingerprint/face recognition', '#007AFF', NULL),
('ARKit', 'Apple augmented reality', '#000000', NULL),
('ARCore', 'Google augmented reality', '#4285F4', NULL),
('Mobile Testing', 'Testing mobile applications', '#00D8FF', NULL),
('App Distribution', 'Deploying mobile apps', '#5AC8FA', NULL),
('Mobile Performance', 'Optimizing mobile apps', '#FF9500', NULL),

-- Security & Cryptography (40 tags)
('Cybersecurity', 'Protecting digital systems', '#FF0000', NULL),
('Encryption', 'Data protection technique', '#4CAF50', NULL),
('Blockchain', 'Distributed ledger technology', '#F7931A', NULL),
('Bitcoin', 'Cryptocurrency', '#F7931A', NULL),
('Ethereum', 'Blockchain platform', '#627EEA', NULL),
('Smart Contracts', 'Self-executing contracts', '#627EEA', NULL),
('Web3', 'Decentralized web', '#F16822', NULL),
('DeFi', 'Decentralized finance', '#627EEA', NULL),
('NFT', 'Non-fungible tokens', '#000000', NULL),
('SSL/TLS', 'Secure communication protocol', '#4CAF50', NULL),
('HTTPS', 'Secure HTTP protocol', '#4CAF50', NULL),
('OAuth', 'Authorization framework', '#000000', NULL),
('JWT', 'JSON Web Tokens', '#000000', NULL),
('Two-Factor Authentication', 'Enhanced security method', '#4285F4', NULL),
('Penetration Testing', 'Security testing technique', '#FF0000', NULL),
('Vulnerability Assessment', 'Security analysis', '#FF5722', NULL),
('Firewall', 'Network security system', '#FF5722', NULL),
('VPN', 'Virtual Private Network', '#0066CC', NULL),
('Zero Trust Security', 'Security model', '#FF0000', NULL),
('GDPR', 'Data protection regulation', '#0066CC', NULL),
('HIPAA', 'Healthcare data protection', '#0066CC', NULL),
('PCI DSS', 'Payment card security standard', '#0066CC', NULL),
('SOC 2', 'Security compliance standard', '#0066CC', NULL),
('ISO 27001', 'Information security standard', '#0066CC', NULL),
('Bug Bounty', 'Vulnerability reward program', '#4CAF50', NULL),
('Ethical Hacking', 'Authorized system testing', '#00FF00', NULL),
('Red Team', 'Offensive security team', '#FF0000', NULL),
('Blue Team', 'Defensive security team', '#0000FF', NULL),
('SIEM', 'Security information management', '#FF5722', NULL),
('Intrusion Detection', 'Security monitoring', '#FF5722', NULL),
('Malware Analysis', 'Studying malicious software', '#FF0000', NULL),
('Phishing Protection', 'Email security', '#FF9800', NULL),
('DDoS Protection', 'Denial of service mitigation', '#FF5722', NULL),
('WAF', 'Web Application Firewall', '#FF5722', NULL),
('API Security', 'Protecting APIs', '#4CAF50', NULL),
('Container Security', 'Securing containers', '#2496ED', NULL),
('Cloud Security', 'Securing cloud infrastructure', '#0089D6', NULL),
('Identity Management', 'User identity systems', '#4285F4', NULL),
('Access Control', 'Permission management', '#4CAF50', NULL),
('Security Auditing', 'Security compliance review', '#FF5722', NULL),

-- Testing & Quality (30 tags)
('Unit Testing', 'Testing individual components', '#25A162', NULL),
('Integration Testing', 'Testing component interactions', '#25A162', NULL),
('End-to-End Testing', 'Full application testing', '#25A162', NULL),
('Test Automation', 'Automated testing', '#25A162', NULL),
('Jest', 'JavaScript testing framework', '#C21325', NULL),
('Mocha', 'JavaScript test framework', '#8D6748', NULL),
('Chai', 'BDD/TDD assertion library', '#A30701', NULL),
('Jasmine', 'Behavior-driven testing', '#8A4182', NULL),
('Cypress', 'E2E testing framework', '#17202C', NULL),
('Selenium', 'Web automation tool', '#43B02A', NULL),
('Playwright', 'Browser automation library', '#2EAD33', NULL),
('Puppeteer', 'Chrome DevTools Protocol', '#40B5A4', NULL),
('TestCafe', 'E2E web testing', '#36B6E0', NULL),
('Appium', 'Mobile app automation', '#662D91', NULL),
('PyTest', 'Python testing framework', '#0A9EDC', NULL),
('JUnit', 'Java testing framework', '#25A162', NULL),
('NUnit', '.NET testing framework', '#1081C2', NULL),
('RSpec', 'Ruby testing tool', '#CC342D', NULL),
('Test-Driven Development', 'TDD methodology', '#25A162', NULL),
('Behavior-Driven Development', 'BDD methodology', '#25A162', NULL),
('Code Coverage', 'Testing completeness metric', '#25A162', NULL),
('Performance Testing', 'Testing system performance', '#FF6B6B', NULL),
('Load Testing', 'Testing under load', '#FF6B6B', NULL),
('Stress Testing', 'Testing breaking points', '#FF6B6B', NULL),
('Security Testing', 'Testing for vulnerabilities', '#FF5722', NULL),
('Regression Testing', 'Testing after changes', '#25A162', NULL),
('Smoke Testing', 'Basic functionality testing', '#25A162', NULL),
('A/B Testing', 'Comparative testing', '#4285F4', NULL),
('Usability Testing', 'User experience testing', '#FF6B6B', NULL),
('Accessibility Testing', 'Inclusive design testing', '#0078D7', NULL),

-- Tools & IDEs (30 tags)
('VS Code', 'Code editor by Microsoft', '#007ACC', NULL),
('Visual Studio', 'Microsoft IDE', '#5C2D91', NULL),
('IntelliJ IDEA', 'Java IDE', '#000000', NULL),
('PyCharm', 'Python IDE', '#000000', NULL),
('WebStorm', 'JavaScript IDE', '#000000', NULL),
('Eclipse', 'Java IDE', '#2C2255', NULL),
('NetBeans', 'Multi-language IDE', '#1B6AC6', NULL),
('Sublime Text', 'Text editor', '#FF9800', NULL),
('Atom', 'Hackable text editor', '#66595C', NULL),
('Vim', 'Text editor', '#019733', NULL),
('Emacs', 'Extensible text editor', '#7F5AB6', NULL),
('Notepad++', 'Windows text editor', '#90E59A', NULL),
('Git', 'Version control system', '#F05032', NULL),
('GitHub', 'Code hosting platform', '#181717', NULL),
('GitLab', 'DevOps platform', '#FCA121', NULL),
('Bitbucket', 'Git repository hosting', '#0052CC', NULL),
('Jira', 'Project management tool', '#0052CC', NULL),
('Trello', 'Project management board', '#0079BF', NULL),
('Asana', 'Work management platform', '#F06A6A', NULL),
('Monday.com', 'Work operating system', '#FF3D57', NULL),
('Notion', 'All-in-one workspace', '#000000', NULL),
('Confluence', 'Team collaboration', '#172B4D', NULL),
('Slack', 'Team communication', '#4A154B', NULL),
('Discord', 'Communication platform', '#5865F2', NULL),
('Microsoft Teams', 'Collaboration platform', '#6264A7', NULL),
('Zoom', 'Video conferencing', '#2D8CFF', NULL),
('Figma', 'Design collaboration tool', '#F24E1E', NULL),
('Sketch', 'Digital design toolkit', '#F7B500', NULL),
('Adobe XD', 'UX/UI design tool', '#FF61F6', NULL),
('Postman', 'API development tool', '#FF6C37', NULL),

-- Emerging Technologies (30 tags)
('Internet of Things', 'Connected devices network', '#00ADD8', NULL),
('5G Technology', 'Fifth generation mobile', '#FF0000', NULL),
('Edge Computing', 'Distributed computing', '#0066CC', NULL),
('Quantum Computing', 'Quantum mechanics computing', '#6929C4', NULL),
('Augmented Reality', 'Enhanced reality overlay', '#FF6B6B', NULL),
('Virtual Reality', 'Immersive digital environment', '#00D4FF', NULL),
('Mixed Reality', 'Blend of real and virtual', '#7B00FF', NULL),
('Digital Twin', 'Virtual replica', '#0066CC', NULL),
('Robotic Process Automation', 'Software robots', '#FF6B00', NULL),
('Voice Assistants', 'AI voice interaction', '#00D9FF', NULL),
('Chatbots', 'Automated conversation', '#4CAF50', NULL),
('Natural UI', 'Natural user interfaces', '#FF6B6B', NULL),
('Gesture Recognition', 'Motion-based interaction', '#9C27B0', NULL),
('Brain-Computer Interface', 'Direct brain communication', '#E91E63', NULL),
('Bioinformatics', 'Biological data analysis', '#4CAF50', NULL),
('Synthetic Biology', 'Engineering biological systems', '#8BC34A', NULL),
('3D Printing', 'Additive manufacturing', '#FF9800', NULL),
('Autonomous Vehicles', 'Self-driving cars', '#4285F4', NULL),
('Drones', 'Unmanned aerial vehicles', '#00BCD4', NULL),
('Smart Cities', 'Technology-integrated cities', '#2196F3', NULL),
('Smart Home', 'Automated home systems', '#4CAF50', NULL),
('Wearable Technology', 'Body-worn devices', '#9C27B0', NULL),
('Nanotechnology', 'Molecular-scale engineering', '#673AB7', NULL),
('Biotechnology', 'Biological technology', '#4CAF50', NULL),
('Clean Tech', 'Environmental technology', '#8BC34A', NULL),
('Energy Storage', 'Power storage systems', '#FF9800', NULL),
('Solar Energy', 'Renewable energy source', '#FFC107', NULL),
('Wind Energy', 'Renewable power generation', '#03A9F4', NULL),
('Carbon Capture', 'CO2 removal technology', '#4CAF50', NULL),
('Hydrogen Fuel', 'Clean energy carrier', '#00BCD4', NULL)
ON CONFLICT (name) DO NOTHING;

-- Verify insertion
SELECT
    COUNT(*) as total_tags,
    COUNT(CASE WHEN created_by IS NULL THEN 1 END) as public_tags
FROM tags;
